source $HOME/.zshbin/antigen.zsh

# For things that are very specific to the current machine. Like docker IP
if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi

if [ "$OSTYPE"="darwin15.0" ]; then
  antigen-bundle osx
fi
# Load various lib files
antigen use oh-my-zsh

#
# Antigen Theme
#

antigen theme candy

#
# Antigen Bundles
#

antigen bundle git

#antigen bundle tmuxinator
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle Tarrasch/zsh-autoenv

# For SSH, starting ssh-agent is annoying
antigen bundle ssh-agent

antigen bundle biguno/dotfiles

antigen apply
